Fix file-diff when local rulebooks are used
If try to use file-diff with vendor auto-guessing (without explicit --hw option) while local rulebooks is exist,
Annet would try to find all rulebooks in folder, and it cause an exception

  File "/Users/anteron/annet-mws/.venv/lib/python3.12/site-packages/annet/rulebook/__init__.py", line 246, in _get_raw_rulebook_text
    raise FileNotFoundError(f'Unable to find rulebook "{name}" in "{self.rulebook_module}" module') from err
FileNotFoundError: Unable to find rulebook "arista" in "rulebooks.texts" module

Now I propose to skip unexist rulebooks